Repository eco/eco-solver, pull requests merged in 2025-07, with the labels that each got.

#171 Integrate Squid as a new liquidity provider
  .nvmrc
  README.md
  config/default.ts
  package.json
  src/eco-configs/eco-config.service.ts
  src/eco-configs/eco-config.types.ts
  src/liquidity-manager/liquidity-manager.module.ts
  src/liquidity-manager/services/liquidity-provider.service.spec.ts
  src/liquidity-manager/services/liquidity-provider.service.ts
  src/liquidity-manager/services/liquidity-providers/CCTP-LiFi/cctp-lifi-rebalancing.integration.spec.ts
  src/liquidity-manager/services/liquidity-providers/Squid/squid-provider.service.spec.ts
  src/liquidity-manager/services/liquidity-providers/Squid/squid-provider.service.ts
  src/liquidity-manager/tests/liquidity-manager.service.spec.ts
  src/liquidity-manager/types/types.d.ts
  src/liquidity-manager/utils/math.spec.ts
  src/liquidity-manager/utils/math.ts
  yarn.lock
Labels: Passed QA, Code Review Complete

#200 Add support for Viem's fallback transport
  package.json
  src/common/chains/tests/transport.spec.ts
  src/common/chains/transport.ts
  src/eco-configs/eco-config.service.ts
  src/eco-configs/tests/eco-config.service.spec.ts
  src/liquidity-manager/services/liquidity-providers/LiFi/lifi-provider.service.spec.ts
  src/sign/nonce.service.ts
  src/transaction/smart-wallets/kernel/create.kernel.account.ts
  src/transaction/viem_multichain_client.service.ts
  yarn.lock
Labels: Passed QA, Code Review Complete

#182 adding validation for max
  src/eco-configs/eco-config.types.ts
  src/intent/tests/validation.service.spec.ts
  src/intent/validation.sevice.ts
  src/quote/additional-quote.service.spec.ts
  src/quote/tests/quote.service.spec.ts
Labels: Passed QA, Code Review Complete, Config Update Required

#209 Deploy world
  package.json
  src/app.module.ts
  src/eco-configs/eco-config.service.ts
  src/eco-configs/tests/eco-config.service.spec.ts
  src/intent-processor/jobs/execute-send-batch.job.ts
  src/intent-processor/jobs/execute-withdraws.job.ts
  src/intent-processor/services/intent-processor.service.ts
  src/intent-processor/services/tests/intent-processor.service.spec.ts
  src/intent/validation.sevice.ts
  yarn.lock
Labels: bug, Code Review Complete

#208 Parallel execution of fulfillment jobs with chain-aware concurrency
  src/app.module.ts
  src/bullmq/processors/solve-intent.processor.ts
  src/common/bullmq/base-job.ts
  src/common/redis/constants.ts
  src/intent-fulfillment/intent-fulfillment.module.ts
  src/intent-fulfillment/jobs/fulfill-intent.job.ts
  src/intent-fulfillment/processors/intent-fulfillment.processor.ts
  src/intent-fulfillment/queues/intent-fulfillment.queue.ts
  src/intent-fulfillment/tests/fulfill-intent.job.spec.ts
  src/intent-fulfillment/tests/intent-fulfillment.processor.spec.ts
  src/intent/feasable-intent.service.ts
  src/intent/intent.module.ts
  src/intent/tests/feasable-intent.service.spec.ts
Labels: Passed QA, Code Review Complete
