Repository eco/eco-solver, pull requests merged in 2025-08, with the labels that each got.

#203 Integrate Everclear as a liquidity provider
  config/default.ts
  src/eco-configs/eco-config.service.ts
  src/eco-configs/eco-config.types.ts
  src/liquidity-manager/jobs/check-everclear-intent.job.ts
  src/liquidity-manager/liquidity-manager.module.ts
  src/liquidity-manager/processors/eco-protocol-intents.processor.ts
  src/liquidity-manager/queues/liquidity-manager.queue.ts
  src/liquidity-manager/services/liquidity-manager.service.spec.ts
  src/liquidity-manager/services/liquidity-provider.service.spec.ts
  src/liquidity-manager/services/liquidity-provider.service.ts
  src/liquidity-manager/services/liquidity-providers/CCTP-LiFi/cctp-lifi-rebalancing.integration.spec.ts
  src/liquidity-manager/services/liquidity-providers/Everclear/everclear-provider.service.spec.ts
  src/liquidity-manager/services/liquidity-providers/Everclear/everclear-provider.service.ts
  src/liquidity-manager/services/liquidity-providers/Everclear/everclear.errors.ts
  src/liquidity-manager/services/liquidity-providers/Squid/squid-provider.service.ts
  src/liquidity-manager/types/types.d.ts
  src/liquidity-manager/utils/transaction.ts
Labels: Passed QA, Ready for Code Review

#220 ED-5662-prevent-multiple-LM-runs
  jest.config.ts
  package.json
  pnpm-lock.yaml
  src/liquidity-manager/jobs/check-balances-cron.job.ts
  src/liquidity-manager/jobs/eco-cron-job-manager.spec.ts
  src/liquidity-manager/jobs/eco-cron-job-manager.ts
  src/liquidity-manager/services/liquidity-manager.service.spec.ts
  src/liquidity-manager/tests/liquidity-manager.service.spec.ts
Labels: Passed QA, Code Review Complete

#213 Documentating the release process
  RELEASING.md
Labels: Ready for Code Review

#242 Implementation of Circle Gateway as a liquidity provider
  config/default.ts
  src/eco-configs/eco-config.service.ts
  src/eco-configs/eco-config.types.ts
  src/liquidity-manager/jobs/gateway-topup.job.ts
  src/liquidity-manager/liquidity-manager.module.ts
  src/liquidity-manager/processors/eco-protocol-intents.processor.ts
  src/liquidity-manager/queues/liquidity-manager.queue.ts
  src/liquidity-manager/services/liquidity-manager.service.ts
  src/liquidity-manager/services/liquidity-provider.service.spec.ts
  src/liquidity-manager/services/liquidity-provider.service.ts
  src/liquidity-manager/services/liquidity-providers/CCTP-LiFi/cctp-lifi-rebalancing.integration.spec.ts
  src/liquidity-manager/services/liquidity-providers/Gateway/README.md
  src/liquidity-manager/services/liquidity-providers/Gateway/constants/abis.ts
  src/liquidity-manager/services/liquidity-providers/Gateway/gateway-provider.service.spec.ts
  src/liquidity-manager/services/liquidity-providers/Gateway/gateway-provider.service.ts
  src/liquidity-manager/services/liquidity-providers/Gateway/gateway.errors.ts
  src/liquidity-manager/services/liquidity-providers/Gateway/utils/gateway-client.integration.spec.ts
  src/liquidity-manager/services/liquidity-providers/Gateway/utils/gateway-client.spec.ts
  src/liquidity-manager/services/liquidity-providers/Gateway/utils/gateway-client.ts
  src/liquidity-manager/types/types.d.ts
Labels: Passed QA, Ready for Code Review

#252 Exponential backoff to smooth transient RPC failures
  config/default.ts
  src/eco-configs/eco-config.service.ts
  src/eco-configs/eco-config.types.ts
  src/watch/intent/tests/watch-create-intent.service.spec.ts
  src/watch/intent/watch-event.service.ts
Labels: Passed QA

#240 Improving robustness of rpc urls
  package.json
  pnpm-lock.yaml
  src/common/chains/tests/transport.spec.ts
  src/common/chains/transport.ts
  src/common/chains/utils.ts
  src/eco-configs/eco-config.service.ts
  src/eco-configs/tests/eco-config.service.spec.ts
Labels: Passed QA, Code Review Complete
